#!/bin/bash
echo "https://deokanee.github.io/Profile/"
echo
echo " ENTER THE KEY : "
trap CODE INT
MQCPTLMGSPGMTTPSMCPNGKLPIMTBR12HYG() {
clear
echo  "Loading."
sleep 1
clear
echo "Loading.."
sleep 1
clear
echo "Loading..."
sleep 1
clear
echo "Loading."
sleep 1
clear
echo "Loading.."
sleep 1
clear
echo "Loading..."
sleep 1
clear
echo ""
echo "DONE " | lolcat
sleep 1
bash instacracker.sh
}
